package com.cetnaline.findproperty.db.dao;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.cetnaline.findproperty.db.entity.DropBo;
import com.cetnaline.findproperty.db.entity.FileDownLoad;
import com.cetnaline.findproperty.db.entity.GScope;
import com.cetnaline.findproperty.db.entity.HistoryHouseTag;
import com.cetnaline.findproperty.db.entity.RailLine;
import com.cetnaline.findproperty.db.entity.RailWay;
import com.cetnaline.findproperty.db.entity.RcToken;
import com.cetnaline.findproperty.db.entity.Staff;
import com.cetnaline.findproperty.db.entity.Store;

import com.cetnaline.findproperty.db.dao.DropBoDao;
import com.cetnaline.findproperty.db.dao.FileDownLoadDao;
import com.cetnaline.findproperty.db.dao.GScopeDao;
import com.cetnaline.findproperty.db.dao.HistoryHouseTagDao;
import com.cetnaline.findproperty.db.dao.RailLineDao;
import com.cetnaline.findproperty.db.dao.RailWayDao;
import com.cetnaline.findproperty.db.dao.RcTokenDao;
import com.cetnaline.findproperty.db.dao.StaffDao;
import com.cetnaline.findproperty.db.dao.StoreDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig dropBoDaoConfig;
    private final DaoConfig fileDownLoadDaoConfig;
    private final DaoConfig gScopeDaoConfig;
    private final DaoConfig historyHouseTagDaoConfig;
    private final DaoConfig railLineDaoConfig;
    private final DaoConfig railWayDaoConfig;
    private final DaoConfig rcTokenDaoConfig;
    private final DaoConfig staffDaoConfig;
    private final DaoConfig storeDaoConfig;

    private final DropBoDao dropBoDao;
    private final FileDownLoadDao fileDownLoadDao;
    private final GScopeDao gScopeDao;
    private final HistoryHouseTagDao historyHouseTagDao;
    private final RailLineDao railLineDao;
    private final RailWayDao railWayDao;
    private final RcTokenDao rcTokenDao;
    private final StaffDao staffDao;
    private final StoreDao storeDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        dropBoDaoConfig = daoConfigMap.get(DropBoDao.class).clone();
        dropBoDaoConfig.initIdentityScope(type);

        fileDownLoadDaoConfig = daoConfigMap.get(FileDownLoadDao.class).clone();
        fileDownLoadDaoConfig.initIdentityScope(type);

        gScopeDaoConfig = daoConfigMap.get(GScopeDao.class).clone();
        gScopeDaoConfig.initIdentityScope(type);

        historyHouseTagDaoConfig = daoConfigMap.get(HistoryHouseTagDao.class).clone();
        historyHouseTagDaoConfig.initIdentityScope(type);

        railLineDaoConfig = daoConfigMap.get(RailLineDao.class).clone();
        railLineDaoConfig.initIdentityScope(type);

        railWayDaoConfig = daoConfigMap.get(RailWayDao.class).clone();
        railWayDaoConfig.initIdentityScope(type);

        rcTokenDaoConfig = daoConfigMap.get(RcTokenDao.class).clone();
        rcTokenDaoConfig.initIdentityScope(type);

        staffDaoConfig = daoConfigMap.get(StaffDao.class).clone();
        staffDaoConfig.initIdentityScope(type);

        storeDaoConfig = daoConfigMap.get(StoreDao.class).clone();
        storeDaoConfig.initIdentityScope(type);

        dropBoDao = new DropBoDao(dropBoDaoConfig, this);
        fileDownLoadDao = new FileDownLoadDao(fileDownLoadDaoConfig, this);
        gScopeDao = new GScopeDao(gScopeDaoConfig, this);
        historyHouseTagDao = new HistoryHouseTagDao(historyHouseTagDaoConfig, this);
        railLineDao = new RailLineDao(railLineDaoConfig, this);
        railWayDao = new RailWayDao(railWayDaoConfig, this);
        rcTokenDao = new RcTokenDao(rcTokenDaoConfig, this);
        staffDao = new StaffDao(staffDaoConfig, this);
        storeDao = new StoreDao(storeDaoConfig, this);

        registerDao(DropBo.class, dropBoDao);
        registerDao(FileDownLoad.class, fileDownLoadDao);
        registerDao(GScope.class, gScopeDao);
        registerDao(HistoryHouseTag.class, historyHouseTagDao);
        registerDao(RailLine.class, railLineDao);
        registerDao(RailWay.class, railWayDao);
        registerDao(RcToken.class, rcTokenDao);
        registerDao(Staff.class, staffDao);
        registerDao(Store.class, storeDao);
    }
    
    public void clear() {
        dropBoDaoConfig.clearIdentityScope();
        fileDownLoadDaoConfig.clearIdentityScope();
        gScopeDaoConfig.clearIdentityScope();
        historyHouseTagDaoConfig.clearIdentityScope();
        railLineDaoConfig.clearIdentityScope();
        railWayDaoConfig.clearIdentityScope();
        rcTokenDaoConfig.clearIdentityScope();
        staffDaoConfig.clearIdentityScope();
        storeDaoConfig.clearIdentityScope();
    }

    public DropBoDao getDropBoDao() {
        return dropBoDao;
    }

    public FileDownLoadDao getFileDownLoadDao() {
        return fileDownLoadDao;
    }

    public GScopeDao getGScopeDao() {
        return gScopeDao;
    }

    public HistoryHouseTagDao getHistoryHouseTagDao() {
        return historyHouseTagDao;
    }

    public RailLineDao getRailLineDao() {
        return railLineDao;
    }

    public RailWayDao getRailWayDao() {
        return railWayDao;
    }

    public RcTokenDao getRcTokenDao() {
        return rcTokenDao;
    }

    public StaffDao getStaffDao() {
        return staffDao;
    }

    public StoreDao getStoreDao() {
        return storeDao;
    }

}
