package com.cetnaline.findproperty.db.dao;

import android.database.Cursor;
import android.database.sqlite.SQLiteStatement;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.Property;
import org.greenrobot.greendao.internal.DaoConfig;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.database.DatabaseStatement;

import com.cetnaline.findproperty.db.entity.GScope;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table "house_menu_gscope".
*/
public class GScopeDao extends AbstractDao<GScope, Long> {

    public static final String TABLENAME = "house_menu_gscope";

    /**
     * Properties of entity GScope.<br/>
     * Can be used for QueryBuilder and for referencing column names.
     */
    public static class Properties {
        public final static Property Id = new Property(0, Long.class, "id", true, "_id");
        public final static Property GScopeId = new Property(1, Integer.class, "GScopeId", false, "GSCOPE_ID");
        public final static Property GScopeCode = new Property(2, String.class, "GScopeCode", false, "GSCOPE_CODE");
        public final static Property GScopeLevel = new Property(3, Integer.class, "GScopeLevel", false, "GSCOPE_LEVEL");
        public final static Property GScopeName = new Property(4, String.class, "GScopeName", false, "GSCOPE_NAME");
        public final static Property GScopeAlias = new Property(5, String.class, "GScopeAlias", false, "GSCOPE_ALIAS");
        public final static Property FullPY = new Property(6, String.class, "FullPY", false, "FULL_PY");
        public final static Property FirstPY = new Property(7, String.class, "FirstPY", false, "FIRST_PY");
        public final static Property ParentId = new Property(8, Integer.class, "ParentId", false, "PARENT_ID");
        public final static Property OrderBy = new Property(9, Integer.class, "OrderBy", false, "ORDER_BY");
        public final static Property Lng = new Property(10, Double.class, "Lng", false, "LNG");
        public final static Property Lat = new Property(11, Double.class, "Lat", false, "LAT");
        public final static Property SaleCount = new Property(12, Integer.class, "SaleCount", false, "SALE_COUNT");
        public final static Property RentCount = new Property(13, Integer.class, "RentCount", false, "RENT_COUNT");
        public final static Property EstateCount = new Property(14, Integer.class, "EstateCount", false, "ESTATE_COUNT");
        public final static Property SaleAvgPrice = new Property(15, Double.class, "SaleAvgPrice", false, "SALE_AVG_PRICE");
        public final static Property SaleAvgPriceRise = new Property(16, Double.class, "SaleAvgPriceRise", false, "SALE_AVG_PRICE_RISE");
        public final static Property PostCount = new Property(17, Integer.class, "PostCount", false, "POST_COUNT");
    }


    public GScopeDao(DaoConfig config) {
        super(config);
    }
    
    public GScopeDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
    }

    /** Creates the underlying database table. */
    public static void createTable(Database db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "\"house_menu_gscope\" (" + //
                "\"_id\" INTEGER PRIMARY KEY ," + // 0: id
                "\"GSCOPE_ID\" INTEGER," + // 1: GScopeId
                "\"GSCOPE_CODE\" TEXT," + // 2: GScopeCode
                "\"GSCOPE_LEVEL\" INTEGER," + // 3: GScopeLevel
                "\"GSCOPE_NAME\" TEXT," + // 4: GScopeName
                "\"GSCOPE_ALIAS\" TEXT," + // 5: GScopeAlias
                "\"FULL_PY\" TEXT," + // 6: FullPY
                "\"FIRST_PY\" TEXT," + // 7: FirstPY
                "\"PARENT_ID\" INTEGER," + // 8: ParentId
                "\"ORDER_BY\" INTEGER," + // 9: OrderBy
                "\"LNG\" REAL," + // 10: Lng
                "\"LAT\" REAL," + // 11: Lat
                "\"SALE_COUNT\" INTEGER," + // 12: SaleCount
                "\"RENT_COUNT\" INTEGER," + // 13: RentCount
                "\"ESTATE_COUNT\" INTEGER," + // 14: EstateCount
                "\"SALE_AVG_PRICE\" REAL," + // 15: SaleAvgPrice
                "\"SALE_AVG_PRICE_RISE\" REAL," + // 16: SaleAvgPriceRise
                "\"POST_COUNT\" INTEGER);"); // 17: PostCount
    }

    /** Drops the underlying database table. */
    public static void dropTable(Database db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "\"house_menu_gscope\"";
        db.execSQL(sql);
    }

    @Override
    protected final void bindValues(DatabaseStatement stmt, GScope entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
 
        Integer GScopeId = entity.getGScopeId();
        if (GScopeId != null) {
            stmt.bindLong(2, GScopeId);
        }
 
        String GScopeCode = entity.getGScopeCode();
        if (GScopeCode != null) {
            stmt.bindString(3, GScopeCode);
        }
 
        Integer GScopeLevel = entity.getGScopeLevel();
        if (GScopeLevel != null) {
            stmt.bindLong(4, GScopeLevel);
        }
 
        String GScopeName = entity.getGScopeName();
        if (GScopeName != null) {
            stmt.bindString(5, GScopeName);
        }
 
        String GScopeAlias = entity.getGScopeAlias();
        if (GScopeAlias != null) {
            stmt.bindString(6, GScopeAlias);
        }
 
        String FullPY = entity.getFullPY();
        if (FullPY != null) {
            stmt.bindString(7, FullPY);
        }
 
        String FirstPY = entity.getFirstPY();
        if (FirstPY != null) {
            stmt.bindString(8, FirstPY);
        }
 
        Integer ParentId = entity.getParentId();
        if (ParentId != null) {
            stmt.bindLong(9, ParentId);
        }
 
        Integer OrderBy = entity.getOrderBy();
        if (OrderBy != null) {
            stmt.bindLong(10, OrderBy);
        }
 
        Double Lng = entity.getLng();
        if (Lng != null) {
            stmt.bindDouble(11, Lng);
        }
 
        Double Lat = entity.getLat();
        if (Lat != null) {
            stmt.bindDouble(12, Lat);
        }
 
        Integer SaleCount = entity.getSaleCount();
        if (SaleCount != null) {
            stmt.bindLong(13, SaleCount);
        }
 
        Integer RentCount = entity.getRentCount();
        if (RentCount != null) {
            stmt.bindLong(14, RentCount);
        }
 
        Integer EstateCount = entity.getEstateCount();
        if (EstateCount != null) {
            stmt.bindLong(15, EstateCount);
        }
 
        Double SaleAvgPrice = entity.getSaleAvgPrice();
        if (SaleAvgPrice != null) {
            stmt.bindDouble(16, SaleAvgPrice);
        }
 
        Double SaleAvgPriceRise = entity.getSaleAvgPriceRise();
        if (SaleAvgPriceRise != null) {
            stmt.bindDouble(17, SaleAvgPriceRise);
        }
 
        Integer PostCount = entity.getPostCount();
        if (PostCount != null) {
            stmt.bindLong(18, PostCount);
        }
    }

    @Override
    protected final void bindValues(SQLiteStatement stmt, GScope entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
 
        Integer GScopeId = entity.getGScopeId();
        if (GScopeId != null) {
            stmt.bindLong(2, GScopeId);
        }
 
        String GScopeCode = entity.getGScopeCode();
        if (GScopeCode != null) {
            stmt.bindString(3, GScopeCode);
        }
 
        Integer GScopeLevel = entity.getGScopeLevel();
        if (GScopeLevel != null) {
            stmt.bindLong(4, GScopeLevel);
        }
 
        String GScopeName = entity.getGScopeName();
        if (GScopeName != null) {
            stmt.bindString(5, GScopeName);
        }
 
        String GScopeAlias = entity.getGScopeAlias();
        if (GScopeAlias != null) {
            stmt.bindString(6, GScopeAlias);
        }
 
        String FullPY = entity.getFullPY();
        if (FullPY != null) {
            stmt.bindString(7, FullPY);
        }
 
        String FirstPY = entity.getFirstPY();
        if (FirstPY != null) {
            stmt.bindString(8, FirstPY);
        }
 
        Integer ParentId = entity.getParentId();
        if (ParentId != null) {
            stmt.bindLong(9, ParentId);
        }
 
        Integer OrderBy = entity.getOrderBy();
        if (OrderBy != null) {
            stmt.bindLong(10, OrderBy);
        }
 
        Double Lng = entity.getLng();
        if (Lng != null) {
            stmt.bindDouble(11, Lng);
        }
 
        Double Lat = entity.getLat();
        if (Lat != null) {
            stmt.bindDouble(12, Lat);
        }
 
        Integer SaleCount = entity.getSaleCount();
        if (SaleCount != null) {
            stmt.bindLong(13, SaleCount);
        }
 
        Integer RentCount = entity.getRentCount();
        if (RentCount != null) {
            stmt.bindLong(14, RentCount);
        }
 
        Integer EstateCount = entity.getEstateCount();
        if (EstateCount != null) {
            stmt.bindLong(15, EstateCount);
        }
 
        Double SaleAvgPrice = entity.getSaleAvgPrice();
        if (SaleAvgPrice != null) {
            stmt.bindDouble(16, SaleAvgPrice);
        }
 
        Double SaleAvgPriceRise = entity.getSaleAvgPriceRise();
        if (SaleAvgPriceRise != null) {
            stmt.bindDouble(17, SaleAvgPriceRise);
        }
 
        Integer PostCount = entity.getPostCount();
        if (PostCount != null) {
            stmt.bindLong(18, PostCount);
        }
    }

    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0);
    }    

    @Override
    public GScope readEntity(Cursor cursor, int offset) {
        GScope entity = new GScope( //
            cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0), // id
            cursor.isNull(offset + 1) ? null : cursor.getInt(offset + 1), // GScopeId
            cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2), // GScopeCode
            cursor.isNull(offset + 3) ? null : cursor.getInt(offset + 3), // GScopeLevel
            cursor.isNull(offset + 4) ? null : cursor.getString(offset + 4), // GScopeName
            cursor.isNull(offset + 5) ? null : cursor.getString(offset + 5), // GScopeAlias
            cursor.isNull(offset + 6) ? null : cursor.getString(offset + 6), // FullPY
            cursor.isNull(offset + 7) ? null : cursor.getString(offset + 7), // FirstPY
            cursor.isNull(offset + 8) ? null : cursor.getInt(offset + 8), // ParentId
            cursor.isNull(offset + 9) ? null : cursor.getInt(offset + 9), // OrderBy
            cursor.isNull(offset + 10) ? null : cursor.getDouble(offset + 10), // Lng
            cursor.isNull(offset + 11) ? null : cursor.getDouble(offset + 11), // Lat
            cursor.isNull(offset + 12) ? null : cursor.getInt(offset + 12), // SaleCount
            cursor.isNull(offset + 13) ? null : cursor.getInt(offset + 13), // RentCount
            cursor.isNull(offset + 14) ? null : cursor.getInt(offset + 14), // EstateCount
            cursor.isNull(offset + 15) ? null : cursor.getDouble(offset + 15), // SaleAvgPrice
            cursor.isNull(offset + 16) ? null : cursor.getDouble(offset + 16), // SaleAvgPriceRise
            cursor.isNull(offset + 17) ? null : cursor.getInt(offset + 17) // PostCount
        );
        return entity;
    }
     
    @Override
    public void readEntity(Cursor cursor, GScope entity, int offset) {
        entity.setId(cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0));
        entity.setGScopeId(cursor.isNull(offset + 1) ? null : cursor.getInt(offset + 1));
        entity.setGScopeCode(cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2));
        entity.setGScopeLevel(cursor.isNull(offset + 3) ? null : cursor.getInt(offset + 3));
        entity.setGScopeName(cursor.isNull(offset + 4) ? null : cursor.getString(offset + 4));
        entity.setGScopeAlias(cursor.isNull(offset + 5) ? null : cursor.getString(offset + 5));
        entity.setFullPY(cursor.isNull(offset + 6) ? null : cursor.getString(offset + 6));
        entity.setFirstPY(cursor.isNull(offset + 7) ? null : cursor.getString(offset + 7));
        entity.setParentId(cursor.isNull(offset + 8) ? null : cursor.getInt(offset + 8));
        entity.setOrderBy(cursor.isNull(offset + 9) ? null : cursor.getInt(offset + 9));
        entity.setLng(cursor.isNull(offset + 10) ? null : cursor.getDouble(offset + 10));
        entity.setLat(cursor.isNull(offset + 11) ? null : cursor.getDouble(offset + 11));
        entity.setSaleCount(cursor.isNull(offset + 12) ? null : cursor.getInt(offset + 12));
        entity.setRentCount(cursor.isNull(offset + 13) ? null : cursor.getInt(offset + 13));
        entity.setEstateCount(cursor.isNull(offset + 14) ? null : cursor.getInt(offset + 14));
        entity.setSaleAvgPrice(cursor.isNull(offset + 15) ? null : cursor.getDouble(offset + 15));
        entity.setSaleAvgPriceRise(cursor.isNull(offset + 16) ? null : cursor.getDouble(offset + 16));
        entity.setPostCount(cursor.isNull(offset + 17) ? null : cursor.getInt(offset + 17));
     }
    
    @Override
    protected final Long updateKeyAfterInsert(GScope entity, long rowId) {
        entity.setId(rowId);
        return rowId;
    }
    
    @Override
    public Long getKey(GScope entity) {
        if(entity != null) {
            return entity.getId();
        } else {
            return null;
        }
    }

    @Override
    public boolean hasKey(GScope entity) {
        return entity.getId() != null;
    }

    @Override
    protected final boolean isEntityUpdateable() {
        return true;
    }
    
}
