package com.cetnaline.findproperty.db.entity;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 

import org.greenrobot.greendao.annotation.Entity;
import org.greenrobot.greendao.annotation.Generated;
import org.greenrobot.greendao.annotation.Transient;

import java.util.List;

/**
 * Entity mapped to table "DROP_BO".
 */
@Entity(
		nameInDb = "house_menu_drop"
)
public class DropBo {

	private Integer type;
	private Integer ID;
	private String Value;
	private String Text;
	private String Name;
	private String Para;
	private String key;

	@Generated(hash = 1276654492)
	public DropBo(Integer type, Integer ID, String Value, String Text, String Name, String Para,
				  String key) {
		this.type = type;
		this.ID = ID;
		this.Value = Value;
		this.Text = Text;
		this.Name = Name;
		this.Para = Para;
		this.key = key;
	}

	@Generated(hash = 1155315543)
	public DropBo() {
	}

	public Integer getType() {
		return this.type;
	}

	public void setType(Integer type) {
		this.type = type;
	}

	public Integer getID() {
		return this.ID;
	}

	public void setID(Integer ID) {
		this.ID = ID;
	}

	public String getValue() {
		return this.Value;
	}

	public void setValue(String Value) {
		this.Value = Value;
	}

	public String getText() {
		return this.Text;
	}

	public void setText(String Text) {
		this.Text = Text;
	}

	public String getName() {
		return this.Name;
	}

	public void setName(String Name) {
		this.Name = Name;
	}

	public String getPara() {
		return this.Para;
	}

	public void setPara(String Para) {
		this.Para = Para;
	}

	public String getKey() {
		return this.key;
	}

	public void setKey(String key) {
		this.key = key;
	}

	public DropBo(String text, String value, int type) {
		this.Text = text;
		this.Value = value;
		this.type = type;
	}

	@Transient
	private boolean isSelected;

	public boolean isSelected() {
		return isSelected;
	}

	public void setSelected(boolean selected) {
		isSelected = selected;
	}

	@Transient
	private List<DropBo> childrenList;
	@Transient
	private String headerStr;

	public String getHeaderStr() {
		return headerStr;
	}

	public void setHeaderStr(String headerStr) {
		this.headerStr = headerStr;
	}

	public List<DropBo> getChildrenList() {
		return childrenList;
	}

	public void setChildrenList(List<DropBo> childrenList) {
		this.childrenList = childrenList;
	}

	@Transient
	private long parentId;

	@Transient
	private double lat;

	@Transient
	private double lng;

	public long getParentId() {
		return parentId;
	}

	public void setParentId(long parentId) {
		this.parentId = parentId;
	}

	public double getLat() {
		return lat;
	}

	public void setLat(double lat) {
		this.lat = lat;
	}

	public double getLng() {
		return lng;
	}

	public void setLng(double lng) {
		this.lng = lng;
	}


}
