package com.cetnaline.findproperty.db.entity;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 

import org.greenrobot.greendao.annotation.Entity;
import org.greenrobot.greendao.annotation.Generated;
import org.greenrobot.greendao.annotation.Id;
import org.greenrobot.greendao.annotation.Transient;

import java.util.List;

/**
 * Entity mapped to table "GSCOPE".
 */
@Entity(
   nameInDb = "house_menu_gscope"
)
public class GScope {

    @Id
    private Long id;
    private Integer GScopeId;
    private String GScopeCode;
    private Integer GScopeLevel;
    private String GScopeName;
    private String GScopeAlias;
    private String FullPY;
    private String FirstPY;
    private Integer ParentId;
    private Integer OrderBy;
    private Double Lng;
    private Double Lat;
    private Integer SaleCount;
    private Integer RentCount;
    private Integer EstateCount;
    private Double SaleAvgPrice;
    private Double SaleAvgPriceRise;
    private Integer PostCount;
   @Generated(hash = 1807689601)
   public GScope(Long id, Integer GScopeId, String GScopeCode, Integer GScopeLevel, String GScopeName,
           String GScopeAlias, String FullPY, String FirstPY, Integer ParentId, Integer OrderBy,
           Double Lng, Double Lat, Integer SaleCount, Integer RentCount, Integer EstateCount,
           Double SaleAvgPrice, Double SaleAvgPriceRise, Integer PostCount) {
       this.id = id;
       this.GScopeId = GScopeId;
       this.GScopeCode = GScopeCode;
       this.GScopeLevel = GScopeLevel;
       this.GScopeName = GScopeName;
       this.GScopeAlias = GScopeAlias;
       this.FullPY = FullPY;
       this.FirstPY = FirstPY;
       this.ParentId = ParentId;
       this.OrderBy = OrderBy;
       this.Lng = Lng;
       this.Lat = Lat;
       this.SaleCount = SaleCount;
       this.RentCount = RentCount;
       this.EstateCount = EstateCount;
       this.SaleAvgPrice = SaleAvgPrice;
       this.SaleAvgPriceRise = SaleAvgPriceRise;
       this.PostCount = PostCount;
   }
   @Generated(hash = 1484189623)
   public GScope() {
   }
   public Long getId() {
       return this.id;
   }
   public void setId(Long id) {
       this.id = id;
   }
   public Integer getGScopeId() {
       return this.GScopeId;
   }
   public void setGScopeId(Integer GScopeId) {
       this.GScopeId = GScopeId;
   }
   public String getGScopeCode() {
       return this.GScopeCode;
   }
   public void setGScopeCode(String GScopeCode) {
       this.GScopeCode = GScopeCode;
   }
   public Integer getGScopeLevel() {
       return this.GScopeLevel;
   }
   public void setGScopeLevel(Integer GScopeLevel) {
       this.GScopeLevel = GScopeLevel;
   }
   public String getGScopeName() {
       return this.GScopeName;
   }
   public void setGScopeName(String GScopeName) {
       this.GScopeName = GScopeName;
   }
   public String getGScopeAlias() {
       return this.GScopeAlias;
   }
   public void setGScopeAlias(String GScopeAlias) {
       this.GScopeAlias = GScopeAlias;
   }
   public String getFullPY() {
       return this.FullPY;
   }
   public void setFullPY(String FullPY) {
       this.FullPY = FullPY;
   }
   public String getFirstPY() {
       return this.FirstPY;
   }
   public void setFirstPY(String FirstPY) {
       this.FirstPY = FirstPY;
   }
   public Integer getParentId() {
       return this.ParentId;
   }
   public void setParentId(Integer ParentId) {
       this.ParentId = ParentId;
   }
   public Integer getOrderBy() {
       return this.OrderBy;
   }
   public void setOrderBy(Integer OrderBy) {
       this.OrderBy = OrderBy;
   }
   public Double getLng() {
       return this.Lng;
   }
   public void setLng(Double Lng) {
       this.Lng = Lng;
   }
   public Double getLat() {
       return this.Lat;
   }
   public void setLat(Double Lat) {
       this.Lat = Lat;
   }
   public Integer getSaleCount() {
       return this.SaleCount;
   }
   public void setSaleCount(Integer SaleCount) {
       this.SaleCount = SaleCount;
   }
   public Integer getRentCount() {
       return this.RentCount;
   }
   public void setRentCount(Integer RentCount) {
       this.RentCount = RentCount;
   }
   public Integer getEstateCount() {
       return this.EstateCount;
   }
   public void setEstateCount(Integer EstateCount) {
       this.EstateCount = EstateCount;
   }
   public Double getSaleAvgPrice() {
       return this.SaleAvgPrice;
   }
   public void setSaleAvgPrice(Double SaleAvgPrice) {
       this.SaleAvgPrice = SaleAvgPrice;
   }
   public Double getSaleAvgPriceRise() {
       return this.SaleAvgPriceRise;
   }
   public void setSaleAvgPriceRise(Double SaleAvgPriceRise) {
       this.SaleAvgPriceRise = SaleAvgPriceRise;
   }
   public Integer getPostCount() {
       return this.PostCount;
   }
   public void setPostCount(Integer PostCount) {
       this.PostCount = PostCount;
   }

    public GScope(Long id) {
        this.id = id;
    }

    @Transient
    private List<GScope> gScopeList;

    public List<GScope> getgScopeList() {
        return gScopeList;
    }

    public void setgScopeList(List<GScope> gScopeList) {
        this.gScopeList = gScopeList;
    }

    @Transient
    private boolean selected;

    public boolean isSelected() {
        return selected;
    }

    public void setSelected(boolean selected) {
        this.selected = selected;
    }

}
